### PR TITLE
feat(gherkin): add gherkin Background

### PR DESCRIPTION
**Pull request by amiceli**
This PR is to add [Background](https://cucumber.io/docs/gherkin/reference/#background) functionnality.
I will implement these rules : 

- only one `Background` for a `Feature`
- only one `Background` for a `Rule`
-  allow `And` and `Given` steps for a Background
-  A warning if a `Background` contains more than 4 lines (tips read in Gherkin doc)

### CODE REVIEW

**Comment by NomanChali** [comment]
When are you planning to merge this PR?

**Comment by amiceli** [comment]
I'm still working on it (event if we don't see commit :)) to run background correctly before each scenario (for feature and rule).
I can publish a a beta version if you want to test it.

Otherwise I will merge it this week.

**Comment by NomanChali** [comment]
> I'm still working on it (event if we don't see commit :)) to run background correctly before each scenario (for feature and rule). I can publish a a beta version if you want to test it.
> 
> Otherwise I will merge it this week.

Thanks for your quick response 
can I try using beta version

**Comment by amiceli** [comment]
Ok, I'm working on a fix for scenario and background call order (with feature and rule).
I will publish a beta version ;)
I will put a message one this PR.

**Comment by amiceli** [comment]
@NomanChali  I've publish `3.3.0-beta.2` version.
You can use `Background` in feature and rule(s).

I'm still working on it but you can test it.
I tried this beta version on some projects, tests still pass ;).

**Comment by amiceli** [comment]
To give some news.
Code is ok, I'm working to improve unit tests for `Background` feature.
And fix `cli-generate` command, I've error with esm, not esm, commonJs etc ^^.

**Pull request merged**
