### PR TITLE
chore: configure ci

### PR DESCRIPTION
**Pull request by Odonno**
* Configure CI with both commitlint and classic CI template (linter, tests, build, coverage)
* Remove lefthook dependency
* Fix coverage result by excluding tests and mocks files

Note: This will remove the dependency over both precommit/prepush hooks and Docker for various reasons: a. not everyone has an installed docker engine, b. git hooks can be slow on the developer machine and most importantly 3. anyone can bypass git hooks while CI prevent this by enforcing rules on every commit/PR. 

Note 2: I am not against lefthook as long as it can be optional.

Note 3: you can add a pretty badge showing code coverage % of the repository :)

### CODE REVIEW

**Comment by amiceli** [comment]
I'm Ok for Github CI and coverage.

But I keep `lefthook`, It's a rule in all my (company, side) projects, don't push code without run unit tests, lint and commitlint.
Even if it can be bypass with `--no-verify`.

**Comment by Odonno** [comment]
I suppose for it to work we could follow this:

1. publish npm package via CI, when a release is created? when a tag is created? your choice (you're gonna need to set your NPM TOKEN in the secrets of this repo)
2. add a specific script command to configure lefthook, maybe just `lefthook` or `lefthook:prepare` 

What do you think?

**Comment by amiceli** [comment]
Ok for `lefthook` you can replace `prepare` with `lefthook:prepare`.

For npm, I prefer to publish package manually not with CI.

CI is useful to check unit tests, lint and commitlint ;).

**Comment by Odonno** [comment]
Should be ok now.

**Comment by amiceli** [comment]
Yes, I merge this PR.

**Pull request merged**
