### PR TITLE
feat(vitest): handle browser mode

### PR DESCRIPTION
**Pull request by amiceli**

### CODE REVIEW

**Comment by charlieforward9** [comment]
Thanks for getting to this so quick! Whats the status right now?

**Comment by amiceli** [comment]
@charlieforward9 I test locally with **vitest-browser-vue** project.
I can load feature file, I'm testing to check regression ;).

I can publish a beta version if you want test it.

**Comment by charlieforward9** [comment]
That would be helpful, thank you.

**Comment by amiceli** [comment]
I published beta version `4.3.0-beta.2`.

In your spec files you should import `loadFeature` like this : 

    import { loadFeature, describeFeature } from "@amiceli/vitest-cucumber/dist/src/browser"

I'm still working on it, but you can test it ;)

**Comment by charlieforward9** [comment]
It works for me! Having downstream issues with `msw` but the `vitest-cucumber` feature files now show up and run in browser mode! Thank you!

**Comment by amiceli** [comment]
Thanks you for your tests.
I finish unit tests and I will publish a stable version ;).

**Comment by amiceli** [comment]
I published stable version `4.3.0`. I'll update docs.
Now you can import from browser module like this : `import { describeFeature, loadFeature } from '@amiceli/vitest-cucumber/browser'`

**Pull request merged**
